#! /bin/bash

: ${XSLTPROC:=xsltproc}
: ${PKGLIBDIR=/usr/lib/fsliomux-conv}

opt_format=c
opt_mode=fn
opt_disable=
opt_only=
opt_outfile=
opt_map=
opt_postproc=
opt_deps=
opt_verbose=false

t=`mktemp -t fsliomux.XXXXXX`
t_err=`mktemp -t fsliomux-err.XXXXXX`
trap "rm -f $t $t_err" EXIT

function panic() {
    printf "$@" >&2
    exit 1
}

while getopts "F:m:O:D:o:M:P:d:v" opt "$@"; do
    case $opt in
      F)	opt_format=$OPTARG;;
      m)	opt_mode=$OPTARG;;
      O)	opt_only=$OPTARG;;
      D)	opt_disable=$OPTARG;;
      M)	opt_map=$OPTARG;;
      o)	opt_outfile=$OPTARG;;
      P)	opt_postproc=$OPTARG;;
      d)	opt_deps=$OPTARG;;
      v)	opt_verbose=true;;
      --)	break;;
      ?)	exit 1;;
    esac
done

shift $[ $OPTIND - 1 ]

xsl_file=
case $opt_format in
  [cC])			xsl_file=iomux2c.xsl;;
  [dD][tT][rR][eE][eE])	xsl_file=iomux2dt.xsl;;
  *)
	panic "Bad format '$opt_format'; supported: 'c', 'dtree'"
esac

xsl_opts=( --stringparam mode "$opt_mode" -o "$t"
  --path "$PKGLIBDIR" --xinclude )

test -z "$opt_disable" || \
    xsl_opts+=( --stringparam disable "$opt_disable" )

test -z "$opt_only" || \
    xsl_opts+=( --stringparam only "$opt_only" )

test -z "$opt_deps" || \
    xsl_opts+=( --load-trace )

$XSLTPROC "${xsl_opts[@]}" "$xsl_file" "$@" 2>$t_err || {\
    cat $t_err >&2
    panic "Failed to convert xml file"
}

if $opt_verbose; then
    cat $t_err
else
    grep -v '^Loaded URL=' $t_err || :
fi >&2

sed 's!Loaded URL="\(/[^"]\+\).*"!\1!' $t_err | while read f; do
    printf '\t%s \\\n' "$f" >>$opt_deps
done

rm -f "$opt_outfile"
set -C
set -e

if test -n "$opt_postproc"; then
    $opt_postproc "$t"
fi

if test -n "$opt_outfile"; then
    exec 90>$opt_outfile
else
    exec 90>&1
fi

if test -n "$opt_map"; then
    bash "$PKGLIBDIR"/iomux-macrofy "$opt_map" < "$t"
else
    cat "$t"
fi >&90
